<?php
/**
 * @file
 * Include Font Awesome icons via CSS classes in your website.
 */

/**
 * Implements hook_config_info().
 */
function font_awesome_config_info() {
  return array(
    'font_awesome.settings' => array(
      'label' => t('Font Awesome settings'),
      'group' => t('Configuration'),
    ),
  );
}

/**
 * Implements hook_init().
 */
function font_awesome_init() {
  // Add FontAwesome CSS.
  $options = array(
    'type' => 'external',
    'every_page' => TRUE,
  );
  switch (config_get('font_awesome.settings', 'fontawesome')) {
    case 'v4':
      backdrop_add_css('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css', $options);
    break;
    case 'v5':
      backdrop_add_css('https://use.fontawesome.com/releases/v5.2.0/css/all.css', $options);
    break;
  }
}

/**
 * Implements hook_menu().
 */
function font_awesome_menu() {
  $items['admin/config/user-interface/font-awesome'] = array(
    'title' => 'Font Awesome',
    'description' => 'Include Font Awesome icons via CSS classes in your website.',
    'page callback' => 'backdrop_get_form',
    'page arguments' => array('font_awesome_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'font_awesome.admin.inc',
  );

  return $items;
}

