<?php
/**
 * @file
 * Install, update, and uninstall functions for the Font Awesome module.
 */

/**
 * Implements hook_update_N().
 */
function font_awesome_update_1001(&$sandbox) {
  // Update variable name.
  $config = config('font_awesome.settings');
  $config->set('enabled', $config->get('font_awesome_1'));
  $config->clear('font_awesome_1');
  $config->save();
}

/**
 * Implements hook_update_last_removed().
 */
function font_awesome_update_last_removed() {
  return 1000;
}

